# refer: https://github.com/dependabot/dependabot-core/blob/main/.github/dependabot.yml
version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates managed by Composer once a week
      interval: "weekly"
      day: "tuesday"
      time: "03:00"
      timezone: "Europe/London"
