// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	azbus "github.com/datatrails/go-datatrails-common/azbus"
	mock "github.com/stretchr/testify/mock"
)

// BatchReceiverOption is an autogenerated mock type for the BatchReceiverOption type
type BatchReceiverOption struct {
	mock.Mock
}

type BatchReceiverOption_Expecter struct {
	mock *mock.Mock
}

func (_m *BatchReceiverOption) EXPECT() *BatchReceiverOption_Expecter {
	return &BatchReceiverOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *BatchReceiverOption) Execute(_a0 *azbus.BatchReceiver) {
	_m.Called(_a0)
}

// BatchReceiverOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type BatchReceiverOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *azbus.BatchReceiver
func (_e *BatchReceiverOption_Expecter) Execute(_a0 interface{}) *BatchReceiverOption_Execute_Call {
	return &BatchReceiverOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *BatchReceiverOption_Execute_Call) Run(run func(_a0 *azbus.BatchReceiver)) *BatchReceiverOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*azbus.BatchReceiver))
	})
	return _c
}

func (_c *BatchReceiverOption_Execute_Call) Return() *BatchReceiverOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *BatchReceiverOption_Execute_Call) RunAndReturn(run func(*azbus.BatchReceiver)) *BatchReceiverOption_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewBatchReceiverOption creates a new instance of BatchReceiverOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBatchReceiverOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *BatchReceiverOption {
	mock := &BatchReceiverOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
