name: "Verify Linked Task"

on: [pull_request]

# For details refer to https://github.com/tim-actions/commit-message-checker-with-regex
jobs:
  check-pr:
    uses: rkvst/avid-builder/.github/workflows/verify-azure-issue.yml@master
