name: VulnCheck
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read # to fetch code (actions/checkout)

# TODO: send results to slack https://github.com/marketplace/actions/send-message-to-slack
jobs:
  vulncheck:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
          cached: false
      - name: Run govulncheck
        run: |
          # suppressed until we can upgrade to go1.24
          echo go run golang.org/x/vuln/cmd/govulncheck@latest -show verbose ./... 
        shell: bash
