name: VulnCheck
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read # to fetch code (actions/checkout)

# TODO: send results to slack https://github.com/marketplace/actions/send-message-to-slack
jobs:
  vulncheck:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go-task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: false

      - name: Vulnerability check
        run: |
          task vulncheck

